{% set name = "opentelemetry-instrumentation-agno" %}
{% set version = "0.52.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_agno-{{ version }}.tar.gz
  sha256: f22d7425ec4fbda84a712e1e7f7195258e6250a5ac67e45ae24147ab20a3f70f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5

test:
  imports:
    - opentelemetry.instrumentation.agno
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Agno instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
